chore: patch gazelle fix for finding repo root (#7779)
Our bazel-examples repo doesn't have a WORKSPACE file currently. Patches
https://github.com/bazel-contrib/bazel-gazelle/pull/2013

---

### Changes are visible to end-users: no

### Test plan

- Manual testing; please provide instructions so we can reproduce:

Built the CLI and ran it in `bazel-examples` repo, this error goes away:
```
Error: -repo_root not specified, and WORKSPACE cannot be found: file does not exist
```
GitOrigin-RevId: 389c7cee67922c4d62c956322d94883ec727ae57