chore: setup --downloader_config and mirror musl.libc.org (#1392)
A robot tells me this specific download has been a frequent source of CI
failures recently.

BCR entries have been mirrored with
`--module_mirrors="https://bcr.cloudflaremirrors.com"` since
`bazelrc-preset.bzl` 1.9.2 added that snippet. But that doesn't cover
every other downloads bazel does.

Example errors:
https://gitlab.com/aspect-build/aspect-cli/-/jobs/15839255112
> java.io.IOException: Error downloading
[https://musl.libc.org/releases/musl-1.2.5.tar.gz] to
/mnt/ephemeral/output/aspect-cli/aspect-cli/external/toolchains_llvm_bootstrapped++musl+musl_libc/temp313838676835598877/musl-1.2.5.tar.gz:
Connect timed out

https://gitlab.com/aspect-build/aspect-cli/-/jobs/15844474173
> java.io.IOException: Error downloading
[https://musl.libc.org/releases/musl-1.2.5.tar.gz] to
/mnt/ephemeral/output/aspect-cli/aspect-cli/external/toolchains_llvm_bootstrapped++musl+musl_libc/temp910020944593838320/musl-1.2.5.tar.gz:
Connect timed out

### Changes are visible to end-users: no

### Test plan

- Covered by existing test cases